<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_view all_img-circle</name>
   <tag></tag>
   <elementGuidId>a509f61e-ad9d-4fff-a26a-57914142e097</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://portal.uad.ac.id/avatar/m.jpeg')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-circle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ebccd995-9f08-4f04-8dd5-2f53fefaf318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-circle</value>
      <webElementGuid>9cb56cde-967d-4843-a762-7f7d61a0b3f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://portal.uad.ac.id/avatar/m.jpeg</value>
      <webElementGuid>fb866677-64f7-4ac1-a9a0-906698f15e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-md page-header-menu-fixed&quot;]/div[@class=&quot;page-header&quot;]/div[@class=&quot;page-header-top&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;top-menu&quot;]/ul[@class=&quot;nav navbar-nav pull-right&quot;]/li[@class=&quot;dropdown dropdown-user dropdown-dark&quot;]/a[@class=&quot;dropdown-toggle&quot;]/img[@class=&quot;img-circle&quot;]</value>
      <webElementGuid>968a92a7-2f30-438a-b3e3-cbe3f3fd5612</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://portal.uad.ac.id/avatar/m.jpeg')]</value>
      <webElementGuid>e112a51c-df6e-4e9d-84ac-58ac03065d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/img</value>
      <webElementGuid>a59c4836-f133-477f-a914-4919aa60ce4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://portal.uad.ac.id/avatar/m.jpeg']</value>
      <webElementGuid>9408f916-8621-4310-9ccd-74630d8e5d0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
