<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>15564b04-64bd-4ac7-9567-c75e33ba356e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.required</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form']/div[3]/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b3a56d10-c3b0-432b-aafc-c48c1c6bad6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d02c7e40-5ab4-402f-80b8-6e257a819a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>96a097be-dcf3-4003-ba88-9e8249ad4027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> * </value>
      <webElementGuid>f8536229-1d88-45cb-947b-1779d0e5987c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form&quot;)/div[@class=&quot;form-group has-warning&quot;]/label[@class=&quot;col-sm-3 control-label&quot;]/span[@class=&quot;required&quot;]</value>
      <webElementGuid>927d9529-b253-4c7e-b721-bf91b142d6c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[3]/label/span</value>
      <webElementGuid>46be21ea-d5a1-4d87-8dd6-2c3366e49e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Expired'])[1]/following::span[1]</value>
      <webElementGuid>d8efac28-e315-4bbf-ba85-74149521285a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Panjang input pada kolom Password Baru tidak boleh melebihi 10 karakter.'])[1]/preceding::span[1]</value>
      <webElementGuid>74374f6c-f010-4dd1-98f8-4838e963e4eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='*']/parent::*</value>
      <webElementGuid>dbc2f8e0-5e5e-42be-ad48-d51f90a26385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>94696edc-d627-4620-afeb-0393378a2352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' * ' or . = ' * ')]</value>
      <webElementGuid>bc264d68-3ed5-4feb-bfaf-2dd3300aa5dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
