<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Upload File (PDF)_file_prestasi</name>
   <tag></tag>
   <elementGuidId>1fac876a-ac1e-47e4-8488-7f1b75d0f8d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='file_prestasi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#file_prestasi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c2af728-7327-4792-bfef-861e5861c178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>file_prestasi</value>
      <webElementGuid>710d134e-5d71-469c-aaf3-4d2e0478daeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>file_prestasi</value>
      <webElementGuid>e679caf4-9d8e-44b5-9796-daa5304dcebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>be9756eb-dd90-4d46-b439-b9e9544e4ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;file_prestasi&quot;)</value>
      <webElementGuid>aeb85e00-1d3e-4980-a4a2-03e922230cce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='file_prestasi']</value>
      <webElementGuid>5744db07-98d4-4681-af47-16ea46562298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div/div[15]/div/span/input</value>
      <webElementGuid>8a0bb20d-9ca4-47da-b200-5a94007940b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>7b5d1a02-78de-4ebf-b987-9a97a0f7f466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'file_prestasi' and @name = 'file_prestasi' and @type = 'file']</value>
      <webElementGuid>daac1d25-bc60-4676-980b-d0c38a9c71aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
