<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login_Data_Portal</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>5eadf1fd-f7c4-4126-bb04-0116daef446e</testSuiteGuid>
   <testCaseLink>
      <guid>36a81308-107e-405d-8974-f6cee8c538be</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Portal UAD/Login/Login_Data_Driven</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>a90fef11-0ef8-4f97-af33-f0294f67c1f7</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Portal UAD/Data_Driven_Excel/Data Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>a90fef11-0ef8-4f97-af33-f0294f67c1f7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>c9f63501-fb6c-418d-995e-98e50ec83716</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a90fef11-0ef8-4f97-af33-f0294f67c1f7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>fa7a23d9-e0fc-41d5-9d56-1c7b07074aad</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
