<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Kemahasiswaan</name>
   <tag></tag>
   <elementGuidId>4e6e5c18-62bd-49e6-be04-644e3d0ae30e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.menu-dropdown.classic-menu-dropdown.open > a.hover-initialized</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Kemahasiswaan')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1494e3fe-ed7f-4d4e-a3a5-259850fb7f40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hover</name>
      <type>Main</type>
      <value>megamenu-dropdown</value>
      <webElementGuid>12176f93-7208-4f60-b050-61bffc3a9d7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-close-others</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>468d3f78-3a3b-494c-afea-dbcd86bb88de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>f6a6f699-b9b5-4000-bc7d-5594ecd359f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://portal.uad.ac.id/</value>
      <webElementGuid>be54437d-bc65-4072-b281-2ad86dc009d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover-initialized</value>
      <webElementGuid>fda28c08-58de-421a-98d6-1c88c04c383e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2453dfa9-165a-424f-96bd-dbda471d63a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
									Kemahasiswaan 
									</value>
      <webElementGuid>15718cce-158f-44a7-bd70-953092997cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-md page-header-menu-fixed&quot;]/div[@class=&quot;page-header&quot;]/div[@class=&quot;page-header-menu&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;hor-menu&quot;]/ul[@class=&quot;nav navbar-nav&quot;]/li[@class=&quot;menu-dropdown classic-menu-dropdown open&quot;]/a[@class=&quot;hover-initialized&quot;]</value>
      <webElementGuid>ffd57a4b-eed7-4767-9ff7-e8fb6bd7a830</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Kemahasiswaan')]</value>
      <webElementGuid>8577d7e3-eb3c-4dbd-8226-174d3d259082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kemahasiswaan']/parent::*</value>
      <webElementGuid>1955c913-2207-485c-b94a-13cbf3d49f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://portal.uad.ac.id/')])[26]</value>
      <webElementGuid>2e6eeff1-808e-4124-b5bc-919b82b04eef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>44379284-7a2c-40cf-a2fb-97875a4764ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://portal.uad.ac.id/' and (text() = '
									Kemahasiswaan 
									' or . = '
									Kemahasiswaan 
									')]</value>
      <webElementGuid>d246896d-306d-4c3c-8e85-b7d65e5af479</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
