<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Kemahasiswaan</name>
   <tag></tag>
   <elementGuidId>607bf094-b2d5-4e5e-81fc-6224eeda93ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Kemahasiswaan')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4faf3736-db4e-47a6-ba2b-056782e8a163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hover</name>
      <type>Main</type>
      <value>megamenu-dropdown</value>
      <webElementGuid>3c36f8b7-2058-4853-8d6b-e3b90daae30e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-close-others</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>37fbbd56-9f99-4537-98b0-fd4ad3971dba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>857bf263-bd82-4d18-96b0-92ddb531f949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://portal.uad.ac.id/</value>
      <webElementGuid>3724f393-8d33-43a3-84cf-3f353bcbf579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hover-initialized</value>
      <webElementGuid>67ce2b97-435e-4e32-9a88-c57a8a36ed92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
									Kemahasiswaan 
									</value>
      <webElementGuid>3edd789f-8bf1-4259-9b41-9c7e6102dfdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-md page-header-menu-fixed&quot;]/div[@class=&quot;page-header&quot;]/div[@class=&quot;page-header-menu&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;hor-menu&quot;]/ul[@class=&quot;nav navbar-nav&quot;]/li[@class=&quot;menu-dropdown classic-menu-dropdown&quot;]/a[@class=&quot;hover-initialized&quot;]</value>
      <webElementGuid>389318d6-f6d3-4f67-bbf3-e417a7fbf24e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Kemahasiswaan')]</value>
      <webElementGuid>e74b8033-1144-471a-a7a0-857f01320995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kemahasiswaan']/parent::*</value>
      <webElementGuid>cf11effb-372c-4649-9f9a-5088daeb19c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://portal.uad.ac.id/')])[26]</value>
      <webElementGuid>30872712-a18a-418d-bfbc-22fd9155c614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>5bf50122-b1e4-4364-8d46-fd002def670f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://portal.uad.ac.id/' and (text() = '
									Kemahasiswaan 
									' or . = '
									Kemahasiswaan 
									')]</value>
      <webElementGuid>2670c206-a9ea-4ba1-894e-a929486ff82f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
