<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Login_m-icon-swapright m-icon-white</name>
   <tag></tag>
   <elementGuidId>55e51274-ae91-4b89-9b18-3f7f374e1db8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.blue.pull-right > i.m-icon-swapright.m-icon-white</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form']/div[3]/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ebbc947e-77cc-4c71-bbfa-02291b132f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-icon-swapright m-icon-white</value>
      <webElementGuid>8c586b41-dabc-4014-b528-d80c086d73d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form&quot;)/div[@class=&quot;form-actions&quot;]/button[@class=&quot;btn blue pull-right&quot;]/i[@class=&quot;m-icon-swapright m-icon-white&quot;]</value>
      <webElementGuid>b52897ac-25fa-48ab-99cf-a0153183e896</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div[3]/button/i</value>
      <webElementGuid>17166e6c-1773-435f-abcf-18b1f31ec683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/i</value>
      <webElementGuid>864157c3-6719-41ea-9262-65d6a0bad16c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
